### ISSUE TITLE
2.0.2 docker update broken

### ISSUE THREAD

**Issue by jonassix** [radixdlt/babylon-nodecli#92]
When trying to update the node via cli as per docs "babylonnode docker install --update" the following exception occurs.
Noticed by sealnode and mleeko

Image shows update 1.0.4 to 1.0.4 , but same issue existed from 1.0.3 to 1.0.4
![image](https://github.com/radixdlt/babylon-nodecli/assets/22755764/a5d529bb-aedb-4577-87fd-e87343510fa1)

**Comment by balda-rdx** [comment]
can you please share the client version that you are using
```
babylonnode version
```

**Comment by jonassix** [comment]
it's in the title. 2.0.2

**Comment by balda-rdx** [comment]
issue is fixed. will be included in the next release
